'use client';

import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
import { DocConfig } from '@/lib/doc-configs';

const styles = StyleSheet.create({
  page: {
    fontFamily: 'Times-Roman',
    fontSize: 10.5,
    paddingTop: 72,
    paddingBottom: 72,
    paddingLeft: 72,
    paddingRight: 72,
    lineHeight: 1.5,
  },
  title: {
    fontFamily: 'Times-Bold',
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 24,
  },
  sectionHeading: {
    fontFamily: 'Times-Bold',
    fontSize: 9,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    color: '#555',
    borderBottomWidth: 0.75,
    borderBottomColor: '#ccc',
    borderBottomStyle: 'solid',
    paddingBottom: 3,
    marginBottom: 10,
    marginTop: 16,
  },
  fieldLabel: {
    fontFamily: 'Times-Bold',
    fontSize: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.3,
    color: '#777',
    marginBottom: 1,
    marginTop: 6,
  },
  fieldValue: {
    fontSize: 10.5,
    borderBottomWidth: 0.5,
    borderBottomColor: '#bbb',
    borderBottomStyle: 'solid',
    paddingBottom: 2,
    minHeight: 14,
    color: '#111',
  },
  divider: {
    borderTopWidth: 0.75,
    borderTopColor: '#bbb',
    borderTopStyle: 'solid',
    marginVertical: 16,
  },
  disclaimer: {
    fontSize: 8,
    fontFamily: 'Times-Italic',
    color: '#666',
    borderWidth: 0.5,
    borderColor: '#e6b800',
    borderStyle: 'solid',
    borderRadius: 3,
    padding: 8,
    marginTop: 16,
    backgroundColor: '#fffbeb',
  },
  disclaimerBold: {
    fontFamily: 'Times-Bold',
    fontSize: 8,
  },
  footer: {
    fontSize: 8,
    color: '#aaa',
    textAlign: 'center',
    marginTop: 24,
  },
  standardTermsNote: {
    fontSize: 9,
    color: '#555',
    fontFamily: 'Times-Italic',
    marginTop: 8,
  },
});

function PdfField({ label, value }: { label: string; value: string }) {
  return (
    <View>
      <Text style={styles.fieldLabel}>{label}</Text>
      <Text style={styles.fieldValue}>{value || '—'}</Text>
    </View>
  );
}

interface Props {
  config: DocConfig;
  fields: Record<string, string>;
}

export function DocumentPdfDocument({ config, fields }: Props) {
  return (
    <Document title={config.name}>
      <Page size="LETTER" style={styles.page}>
        <Text style={styles.title}>{config.name}</Text>

        {config.sections.map(section => {
          const sectionFields = config.fields.filter(f => f.section === section.key);
          return (
            <View key={section.key}>
              <Text style={styles.sectionHeading}>{section.title}</Text>
              {sectionFields.map(f => (
                <PdfField key={f.key} label={f.label} value={fields[f.key] ?? ''} />
              ))}
            </View>
          );
        })}

        <View style={styles.divider} />
        <Text style={styles.sectionHeading}>Standard Terms</Text>
        <Text style={styles.standardTermsNote}>
          The standard terms for this {config.name} are identical to the Common Paper standard
          terms incorporated by reference into this agreement.
        </Text>

        <View style={styles.disclaimer}>
          <Text>
            <Text style={styles.disclaimerBold}>Legal Disclaimer: </Text>
            This document was generated by Prelegal for informational purposes only and does not
            constitute legal advice. Please consult a qualified attorney before signing any legal
            agreement.
          </Text>
        </View>

        <Text style={styles.footer}>
          Generated by Prelegal — powered by Common Paper standard terms.
        </Text>
      </Page>
    </Document>
  );
}
